image: node:9.4.0

cache:
    paths:
    - node_modules/

stages:
    - build
    - test

build:
    stage: build
    script:
        - yarn
        - npm run ci

test:
    stage: test
    script:
        - yarn
        - npm test

services:
    - mongo:latest
